name: Build Release APK

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v6
              with:
                  ref: main

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Setup Java JDK
              uses: actions/setup-java@v5
              with:
                  java-version: '17'
                  distribution: oracle
                  cache: 'gradle'

            - name: Install Dependencies
              run: npm install

            - name: Build APK & AAB
              run: |
                  mkdir android/app/src/main/assets
                  cd android
                  ./gradlew bundleRelease
                  ./gradlew assembleRelease

            - name: Upload Artifact
              uses: actions/upload-artifact@v7
              with:
                  path: android/app/build/outputs/
